console.log("===== ARITHMETIC OPERATORS =====");

let a = 10;
let b = 3;

console.log("Addition:", a + b);
console.log("Subtraction:", a - b);
console.log("Multiplication:", a * b);
console.log("Division:", a / b);
console.log("Remainder:", a % b);
console.log("Power:", a ** b);


console.log("===== ASSIGNMENT OPERATORS =====");

let number = 10;

console.log("Starting:", number);

number += 5;
console.log("After += 5:", number);

number -= 3;
console.log("After -= 3:", number);

number *= 2;
console.log("After *= 2:", number);

number /= 4;
console.log("After /= 4:", number);

number %= 3;
console.log("After %= 3:", number);
